//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace W.Areas.Member.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameEntities : DbContext
    {
        public GameEntities()
            : base("name=GameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tActiveRegion> tActiveRegion { get; set; }
        public virtual DbSet<tActiveRegionVSMember> tActiveRegionVSMember { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
        public virtual DbSet<tPlayRecord> tPlayRecord { get; set; }
        public virtual DbSet<tWishlist> tWishlist { get; set; }
        public virtual DbSet<tGame> tGame { get; set; }
    }
}
