//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace W.Areas.Member.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tActiveRegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tActiveRegion()
        {
            this.tActiveRegionVSMember = new HashSet<tActiveRegionVSMember>();
        }
    
        public int fActiveRegionID { get; set; }
        public string fActiveRegion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tActiveRegionVSMember> tActiveRegionVSMember { get; set; }
    }
}
