//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace W.Areas.Member.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPlayRecord
    {
        public int fPlayRecordID { get; set; }
        public Nullable<int> fMemberID { get; set; }
        public Nullable<int> fGameID { get; set; }
        public Nullable<System.DateTime> fPlayDate { get; set; }
        public string fPlayLocation { get; set; }
        public Nullable<int> fPlayCount { get; set; }
        public string fPlayDescription { get; set; }
        public string fKey { get; set; }
    
        public virtual tMember tMember { get; set; }
        public virtual tGame tGame { get; set; }
    }
}
