//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAD
    {
        public int fADID { get; set; }
        public string fCompanyName { get; set; }
        public string fADPicture { get; set; }
        public string fADURL { get; set; }
        public Nullable<int> fClickCount { get; set; }
        public Nullable<decimal> fDonate { get; set; }
    }
}
