//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tArticle
    {
        public int fArticleListID { get; set; }
        public Nullable<int> fArticleTypeID { get; set; }
        public Nullable<int> fAssociationID { get; set; }
        public Nullable<int> fMemberID { get; set; }
        public string fArticleHead { get; set; }
        public string fArticleDescription { get; set; }
        public string fArticleDate { get; set; }
        public Nullable<int> fArticleParentID { get; set; }
    
        public virtual tMember tMember { get; set; }
    }
}
