//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBuyRecord
    {
        public int fBuyRecordID { get; set; }
        public int fSalerID { get; set; }
        public Nullable<int> fBuyerID { get; set; }
        public int fProductID { get; set; }
        public string fBuyDate { get; set; }
        public Nullable<int> fBuyCount { get; set; }
        public Nullable<int> fProductPrice { get; set; }
    
        public virtual tGame tGame { get; set; }
        public virtual tMember tMember { get; set; }
        public virtual tMember tMember1 { get; set; }
    }
}
