//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGame()
        {
            this.tBuyRecord = new HashSet<tBuyRecord>();
            this.tDesignerVSGame = new HashSet<tDesignerVSGame>();
            this.tPublisherVSGame = new HashSet<tPublisherVSGame>();
            this.tWishlist = new HashSet<tWishlist>();
            this.tTrade = new HashSet<tTrade>();
            this.tScoreRecord = new HashSet<tScoreRecord>();
            this.tPlayRecord = new HashSet<tPlayRecord>();
            this.tGameThemeVSGame = new HashSet<tGameThemeVSGame>();
            this.tGameMechanismsVSGame = new HashSet<tGameMechanismsVSGame>();
            this.tGameFile = new HashSet<tGameFile>();
            this.tGameCategoriesVSGame = new HashSet<tGameCategoriesVSGame>();
        }
    
        public int fGameID { get; set; }
        public string fGameName_TC { get; set; }
        public string fGameName_EN { get; set; }
        public Nullable<byte> fMaxPlayer { get; set; }
        public Nullable<byte> fMinPlayer { get; set; }
        public Nullable<int> fGameAge { get; set; }
        public Nullable<byte> fMaxPlayTime { get; set; }
        public Nullable<byte> fMinPlayTime { get; set; }
        public string fGameDescription { get; set; }
        public string fCardSize { get; set; }
        public Nullable<int> fCardCount { get; set; }
        public Nullable<int> fPublishYear { get; set; }
        public Nullable<decimal> fRank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBuyRecord> tBuyRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDesignerVSGame> tDesignerVSGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPublisherVSGame> tPublisherVSGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tWishlist> tWishlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTrade> tTrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tScoreRecord> tScoreRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPlayRecord> tPlayRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameThemeVSGame> tGameThemeVSGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameMechanismsVSGame> tGameMechanismsVSGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameFile> tGameFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameCategoriesVSGame> tGameCategoriesVSGame { get; set; }
    }
}
