//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPair()
        {
            this.tPairJoinMember = new HashSet<tPairJoinMember>();
            this.tPairRecord = new HashSet<tPairRecord>();
        }
    
        public int fPairID { get; set; }
        public int fMemberID { get; set; }
        public string fSquadName { get; set; }
        public string fSquadStartDate { get; set; }
        public string fSquadEndDate { get; set; }
        public Nullable<int> fSquadMaxPlayer { get; set; }
        public Nullable<int> fSquadMinPlayer { get; set; }
        public string fSquadMember { get; set; }
        public string fPlayLocation { get; set; }
        public string fSquadDescription { get; set; }
    
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPairJoinMember> tPairJoinMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPairRecord> tPairRecord { get; set; }
    }
}
